/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as impFactorySol from "./IMPFactory.sol";
export type { impFactorySol };
export type { IEAS } from "./IEAS";
export type { IMACI } from "./IMACI";
export type { IMessageProcessor } from "./IMessageProcessor";
export type { IPoll } from "./IPoll";
export type { IPollFactory } from "./IPollFactory";
export type { ITallySubsidyFactory } from "./ITallySubsidyFactory";
export type { IVerifier } from "./IVerifier";
export type { IVkRegistry } from "./IVkRegistry";
