/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface ContractFactoryInterface extends Interface {
  getFunction(
    nameOrSignature: "deploy" | "isDeployer" | "setDeployer" | "usedSalts"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "Deployed"): EventFragment;

  encodeFunctionData(
    functionFragment: "deploy",
    values: [string, string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isDeployer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setDeployer",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "usedSalts",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "deploy", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isDeployer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setDeployer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usedSalts", data: BytesLike): Result;
}

export namespace DeployedEvent {
  export type InputTuple = [deployed: AddressLike, salt: BytesLike];
  export type OutputTuple = [deployed: string, salt: string];
  export interface OutputObject {
    deployed: string;
    salt: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ContractFactory extends BaseContract {
  connect(runner?: ContractRunner | null): ContractFactory;
  waitForDeployment(): Promise<this>;

  interface: ContractFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  deploy: TypedContractMethod<
    [_contractName: string, _version: string, creationCode: BytesLike],
    [string],
    "payable"
  >;

  isDeployer: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  setDeployer: TypedContractMethod<
    [_deployer: AddressLike, _allowedToDeploy: boolean],
    [void],
    "nonpayable"
  >;

  usedSalts: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "deploy"
  ): TypedContractMethod<
    [_contractName: string, _version: string, creationCode: BytesLike],
    [string],
    "payable"
  >;
  getFunction(
    nameOrSignature: "isDeployer"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "setDeployer"
  ): TypedContractMethod<
    [_deployer: AddressLike, _allowedToDeploy: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "usedSalts"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  getEvent(
    key: "Deployed"
  ): TypedContractEvent<
    DeployedEvent.InputTuple,
    DeployedEvent.OutputTuple,
    DeployedEvent.OutputObject
  >;

  filters: {
    "Deployed(address,bytes32)": TypedContractEvent<
      DeployedEvent.InputTuple,
      DeployedEvent.OutputTuple,
      DeployedEvent.OutputObject
    >;
    Deployed: TypedContractEvent<
      DeployedEvent.InputTuple,
      DeployedEvent.OutputTuple,
      DeployedEvent.OutputObject
    >;
  };
}
