/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ITallySubsidyFactory,
  ITallySubsidyFactoryInterface,
} from "../../../../maci-contracts/contracts/interfaces/ITallySubsidyFactory";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_verifier",
        type: "address",
      },
      {
        internalType: "address",
        name: "_vkRegistry",
        type: "address",
      },
      {
        internalType: "address",
        name: "_poll",
        type: "address",
      },
      {
        internalType: "address",
        name: "_messageProcessor",
        type: "address",
      },
      {
        internalType: "address",
        name: "_owner",
        type: "address",
      },
    ],
    name: "deploy",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ITallySubsidyFactory__factory {
  static readonly abi = _abi;
  static createInterface(): ITallySubsidyFactoryInterface {
    return new Interface(_abi) as ITallySubsidyFactoryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ITallySubsidyFactory {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as ITallySubsidyFactory;
  }
}
