/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IAllo } from "./IAllo";
export type { IAnchor } from "./IAnchor";
export type { IRegistry } from "./IRegistry";
export type { IStrategy } from "./IStrategy";
