/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as daiSol from "./dai.sol";
export type { daiSol };
export type { CreateStrategy } from "./CreateStrategy";
